"use client";

import { useRef } from "react";
import jsPDF from "jspdf";

function stripMarkdown(md: string): string {
  return md
    .replace(/^#{1,3} /gm, "")
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/^- /gm, "• ")
    .trim();
}

function exportPdf(content: string, title: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = 210;
  const pageH = 297;
  const margin = 20;
  const maxW = pageW - margin * 2;
  const lineH = 7;

  // Light yellow background
  doc.setFillColor(255, 253, 232);
  doc.rect(0, 0, pageW, pageH, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(23, 26, 33);
  doc.text(title, margin, margin + 8);

  // Content
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 70, 85);
  const lines = doc.splitTextToSize(stripMarkdown(content), maxW);

  let y = margin + 22;
  for (const line of lines) {
    if (y > pageH - margin) {
      doc.addPage();
      doc.setFillColor(255, 253, 232);
      doc.rect(0, 0, pageW, pageH, "F");
      y = margin;
    }
    // Bold detection (simple: if line starts with specific pattern)
    if (typeof line === "string" && (line.startsWith("玩家") || line.startsWith("游戏") || line.startsWith("评测"))) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(23, 26, 33);
    } else {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(60, 70, 85);
    }
    doc.text(line, margin, y);
    y += lineH;
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(160, 170, 180);
  doc.text("Generated by MySteamStats", margin, pageH - margin + 5);

  doc.save("mysteamstats-analysis.pdf");
}

function renderMarkdown(md: string): string {
  return md
    .replace(/### (.+)/g, '<h3 class="text-base font-bold text-[#171a21] mt-5 mb-2">$1</h3>')
    .replace(/## (.+)/g, '<h2 class="text-lg font-bold text-[#171a21] mt-6 mb-3">$1</h2>')
    .replace(/# (.+)/g, '<h1 class="text-xl font-bold text-[#171a21] mt-6 mb-3">$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong class="text-[#1a9fff]">$1</strong>')
    .replace(/^- (.+)/gm, '<li class="text-[#5f7d9a] text-sm ml-4">$1</li>')
    .replace(/\n\n/g, '</p><p class="text-[#5f7d9a] text-sm leading-relaxed mb-2">')
    .replace(/^(.+)$/gm, (line) => (line.startsWith('<') ? line : ''));
}

function wrapParagraphs(md: string): string {
  const html = renderMarkdown(md);
  return `<p class="text-[#5f7d9a] text-sm leading-relaxed mb-2">${html}</p>`;
}

export default function AnalysisCard({
  content,
  loading,
  onRefresh,
  title = "分析报告",
}: {
  content: string | null;
  loading: boolean;
  onRefresh: () => void;
  title?: string;
}) {
  if (loading) {
    return (
      <div className="bg-white rounded-2xl border border-[#e2e8f0] p-10 text-center">
        <div className="w-8 h-8 border-2 border-[#1a9fff] border-t-transparent rounded-full animate-spin mx-auto mb-3" />
        <p className="text-[#5f7d9a] text-sm">AI 正在分析你的游戏数据...</p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-2xl border border-[#e2e8f0] p-6">
      {content ? (
        <>
          <div className="prose prose-sm max-w-none" dangerouslySetInnerHTML={{ __html: wrapParagraphs(content) }} />
          <div className="mt-6 flex items-center justify-center gap-4">
            <button
              onClick={onRefresh}
              disabled={loading}
              className="text-[#1a9fff] text-sm hover:underline transition"
            >
              刷新分析
            </button>
            <button
              onClick={() => exportPdf(content, title)}
              className="bg-[#1a9fff] hover:bg-[#1789dd] text-white px-4 py-2 rounded-full text-sm font-medium transition"
            >
              导出 PDF
            </button>
          </div>
        </>
      ) : (
        <div className="text-center py-8">
          <p className="text-[#5f7d9a] text-sm mb-4">点击下方按钮开始分析</p>
          <button
            onClick={onRefresh}
            className="bg-[#1a9fff] hover:bg-[#1789dd] text-white px-6 py-2.5 rounded-full text-sm font-medium transition"
          >
            开始分析
          </button>
        </div>
      )}
    </div>
  );
}
