"use client";

import jsPDF from "jspdf";

function stripMarkdown(md: string): string {
  return md
    .replace(/^#{1,3} /gm, "")
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/^- /gm, "• ")
    .trim();
}

function exportPdf(content: string, title: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = 210, pageH = 297, margin = 20;
  const maxW = pageW - margin * 2;
  const lineH = 7;

  doc.setFillColor(255, 253, 232);
  doc.rect(0, 0, pageW, pageH, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(23, 26, 33);
  doc.text(title, margin, margin + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 70, 85);
  const lines = doc.splitTextToSize(stripMarkdown(content), maxW);

  let y = margin + 22;
  for (const line of lines) {
    if (y > pageH - margin) {
      doc.addPage();
      doc.setFillColor(255, 253, 232);
      doc.rect(0, 0, pageW, pageH, "F");
      y = margin;
    }
    doc.text(line, margin, y);
    y += lineH;
  }

  doc.setFontSize(9);
  doc.setTextColor(160, 170, 180);
  doc.text("Generated by MySteamStats", margin, pageH - margin + 5);
  doc.save("mysteamstats-analysis.pdf");
}

// Simple but correct markdown → HTML
function toHtml(md: string): string {
  const lines = md.split("\n");
  let html = "";
  let inList = false;

  for (const line of lines) {
    // Heading
    if (/^### (.+)/.test(line)) {
      if (inList) { html += "</ul>"; inList = false; }
      html += `<h3 class="text-base font-bold text-[#171a21] mt-5 mb-2">${line.slice(4)}</h3>`;
      continue;
    }
    if (/^## (.+)/.test(line)) {
      if (inList) { html += "</ul>"; inList = false; }
      html += `<h2 class="text-lg font-bold text-[#171a21] mt-6 mb-3">${line.slice(3)}</h2>`;
      continue;
    }
    if (/^# (.+)/.test(line)) {
      if (inList) { html += "</ul>"; inList = false; }
      html += `<h1 class="text-xl font-bold text-[#171a21] mt-6 mb-3">${line.slice(2)}</h1>`;
      continue;
    }
    // List item
    if (/^- (.+)/.test(line)) {
      if (!inList) { html += "<ul class='list-disc ml-5 space-y-1'>"; inList = true; }
      const item = line.slice(2).replace(/\*\*(.+?)\*\*/g, "<strong class='text-[#1a9fff]'>$1</strong>");
      html += `<li class="text-[#5f7d9a] text-sm">${item}</li>`;
      continue;
    }
    // Empty line
    if (line.trim() === "") {
      if (inList) { html += "</ul>"; inList = false; }
      html += "<div class='h-3'></div>";
      continue;
    }
    // Regular paragraph line
    if (inList) { html += "</ul>"; inList = false; }
    const text = line.replace(/\*\*(.+?)\*\*/g, "<strong class='text-[#1a9fff]'>$1</strong>");
    html += `<p class="text-[#5f7d9a] text-sm leading-relaxed mb-1">${text}</p>`;
  }

  if (inList) html += "</ul>";
  return html;
}

export default function AnalysisCard({
  content,
  loading,
  onRefresh,
  title = "分析报告",
}: {
  content: string | null;
  loading: boolean;
  onRefresh: () => void;
  title?: string;
}) {
  if (loading) {
    return (
      <div className="bg-white rounded-2xl border border-[#e2e8f0] p-10 text-center">
        <div className="w-8 h-8 border-2 border-[#1a9fff] border-t-transparent rounded-full animate-spin mx-auto mb-3" />
        <p className="text-[#5f7d9a] text-sm">AI 正在分析你的游戏数据...</p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-2xl border border-[#e2e8f0] p-6">
      {content ? (
        <>
          <div className="prose prose-sm max-w-none" dangerouslySetInnerHTML={{ __html: toHtml(content) }} />
          <div className="mt-6 flex items-center justify-center gap-4">
            <button onClick={onRefresh} disabled={loading} className="text-[#1a9fff] text-sm hover:underline transition">
              刷新分析
            </button>
            <button onClick={() => exportPdf(content, title)} className="bg-[#1a9fff] hover:bg-[#1789dd] text-white px-4 py-2 rounded-full text-sm font-medium transition">
              导出 PDF
            </button>
          </div>
        </>
      ) : (
        <div className="text-center py-8">
          <p className="text-[#5f7d9a] text-sm mb-4">点击下方按钮开始分析</p>
          <button onClick={onRefresh} className="bg-[#1a9fff] hover:bg-[#1789dd] text-white px-6 py-2.5 rounded-full text-sm font-medium transition">
            开始分析
          </button>
        </div>
      )}
    </div>
  );
}
